version: "3"

services:
  whoami:
    image: "traefik/whoami"
    hostname: "cloud"
    container_name: "cloud"
    restart: unless-stopped
    depends_on:
      - traefik
    #ports:
    #  - "${WHOAMI_PORT}:80" # HTTP port (host:container)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`cloud.${MYDOMAIN}`)"
      - "traefik.http.routers.cloud.entrypoints=websecure"
      - "traefik.http.routers.cloud.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.cloud.tls=true"
        #- "traefik.http.services.cloud.loadbalancer.server.port=8081"
        #- "traefik.http.routers.whoami.middlewares=ip_whitelist_admin@file"
    networks:
      - traefik-net
