# https://github.com/qdm12/ddns-updater

version: "3.7"

networks:
  backend-net:
    driver: bridge
    ipam:
      config:
        - subnet: ${BACKEND_NET}
        
services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    hostname: ddns-updater
    container_name: ddns-updater
    network_mode: bridge
    restart: always
    ports:
      - ${DDNS_UPDATER_PORT}:8000/tcp
    volumes:
      - ${DATAPATH}/ddns-updater:/updater/data
    environment:
      - TZ=${TIME_ZONE}
      - CONFIG=
      - PERIOD=${DDNS_PERIOD}
      - UPDATE_COOLDOWN_PERIOD=${DDNS_PERIOD}
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s

      # Web UI
      - LISTENING_PORT=${DDNS_UPDATER_PORT}
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
