version: '3'

networks:
  backend-net:
    external: false

services:
  mariadb:
    image: mariadb:latest
    hostname: mariadb
    container_name: mariadb
    restart: unless-stopped
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=${TIME_ZONE}
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      #- MARIADB_USER:  YOUR_MYSQL_USER_HERE 
      #- MARIADB_PASSWORD: YOUR_USER_PW_HERE
    volumes:
     - ${DATAPATH}/mariadb/mysql:/var/lib/mysql:rw
    networks:
      - backend-net