version: '3'

services:

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    hostname: nextcloud
    restart: unless-stopped
    environment:
      - TZ=${TIME_ZONE}
      - PUID=${PUID}
      - PGID=${PGID}
      - REDIS_HOST=redis
      #- REDIS_PASSWORD=${REDIS_PWD}
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost ${NEXTCLOUD_DOMAIN} # each option should be separate by a space as per documentation - not sure if I need more/less at this point
      - TRUSTED_PROXIES=192.168.99.A ${NEXTCLOUD_DOMAIN} # each option should be separate by a space as per documentation - not sure if I need more/less at this point
      - OVERWRITEHOST=${NEXTCLOUD_DOMAIN} # from: https://help.nextcloud.com/t/docker-reverse-proxy-and-trusted-domains/117891/26
      - OVERWRITEPROTOCOL=https
      #- OVERWRITEWEBROOT=nextcloud
    volumes:
      # Store the contents of Nextcloud and enable local modifications
      - /mnt/data/nextcloud/config:/config
      - /mnt/data/nextcloud/data:/data
      - /mnt/data/fotos/Album:/mnt/AlbumFamiliar
    networks:
      - traefik-net
      - backend-net
    links:
      - mariadb
      - redis
    labels:
      # Connect to Traefik
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Set "Strict-Transport-Security" HTTP header for enhanced security
      - "traefik.http.middlewares.sts_headers.headers.stsSeconds=15552000"
      - "traefik.http.middlewares.sts_headers.headers.stsIncludeSubdomains=True"
      # Middlewares Caldav
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=True"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      # Route HTTPS
      - "traefik.http.routers.nextcloud-secure.entrypoints=websecure"
      - "traefik.http.routers.nextcloud-secure.rule=Host(`${NEXTCLOUD_DOMAIN}`)"
      - "traefik.http.routers.nextcloud-secure.middlewares=nextcloud_redirectregex@docker,sts_headers@docker"
      #- "traefik.http.services.nextcloud.loadbalancer.server.port=8003"
      # Enable TLS
      - "traefik.http.routers.nextcloud-secure.tls=true"
      # Enable Let's Encrypt HTTP challenge
      - "traefik.http.routers.traefik-secure-secured.tls.certresolver=myLetsEncripCert"
      # Enable HSTS headers and other security headers
      #- "traefik.http.routers.nextcloud-secure.middlewares=myheaders@file"
