version: "3.8"

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=${TIME_ZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`${MYDOMAIN}`)"
      - "traefik.http.routers.nginx.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.nginx.tls=true"
    networks:
      - traefik-net
      - backend-net


