version: "3"

networks:
  traefik-net:
    driver: bridge
    external: true
  backend-net:
      external: false
      ipam:
        config:
          - subnet: ${BACKEND_NET}  

services:
  nginx:
    image: nginx:latest
    hostname: nginx
    container_name: nginx
    depends_on:
      - traefik
    environment:
      - TZ=${TIME_ZONE}  
    volumes:
      #- ${DATAPATH}/nginx/src:/var/www/html
      #- ${DATAPATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`${MYDOMAIN}`)"
      - "traefik.http.routers.nginx.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.nginx.tls=true"
    networks:
      traefik-net: null
      backend-net:
        aliases:
          - nginx
        ipv4_address: ${NGINX_IP}


