version: "3"

services:
  nginx:
    image: nginx:latest
    hostname: nginx2
    container_name: nginx2
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=${TIME_ZONE}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx2.rule=Host(`${MYDOMAIN}`) && PathPrefix(`/myadmin2`)"
      - "traefik.http.routers.nginx2.entrypoints=websecure"
      - "traefik.http.routers.nginx2.service=nginx2"
      - "traefik.http.services.nginx2.loadbalancer.server.port=80"   
      - "traefik.http.routers.nginx2.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.nginx2.tls=true"
    networks:
      - traefik-net
      - backend-net


