version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    depends_on:
      - traefik
    environment:
      - TZ=${TIME_ZONE}  
    #volumes:
      #- ${DATAPATH}/nginx/src:/var/www/html
      #- ${DATAPATH}/nginx/default.conf:/etc/nginx/conf.d/default.conf   
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.entrypoints=websecure"
      - "traefik.http.routers.nginx.rule=Host(`${MYDOMAIN}`)"
      - "traefik.http.routers.nginx.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.nginx.tls=true"
    networks:
      - traefik-net


