version: "3"

services:
  redis:
    image: redis:alpine
    container_name: redis
    hostname: redis
    restart: unless-stopped
    #environment:
    #  - REDIS_PASSWORD=${REDIS_PWD}  #YOUR_REDIS_PASSWORD_HERE
    volumes:
      - ${DATAPATH}/redis:/data
    networks:
      - backend-net
    