version: "3.9"

networks:
  traefik-net:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v2.9
    restart: unless-stopped
    networks:
      - traefik-net
    environment:
      - TZ=${TIME_ZONE}
      - PUID=$PUID
      - PGID=$PGID
    ports:
      - "80:80" # "web" HTTP listener
      - "443:443" # "websecure" SSL listener
      - "8080:8080" # Traefik dashboard
    volumes:
      # Allows Traefik to listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Provide the static config file.
      - ${DATAPATH}/traefik/static.yml:/etc/traefik/traefik.yml:ro 
      # dynamic config
      - ${DATAPATH}/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro 
      # letsencrypt data  
      - ${DATAPATH}/traefik/acme:/etc/traefik/acme
      # logs
      - ${DATAPATH}/traefik/log:/log     
