version: "3"

networks:
  traefik-net:
    driver: bridge
  backend-net:
      ipam:
        config:
          - subnet: ${BACKEND_NET}  

services:
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    restart: unless-stopped
    network_mode: host
    environment:
      - TZ: ${TIME_ZONE}
      - PUID: $PUID
      - PGID: $PGID
    command:
      # Enabling docker provider
      - "--providers.docker=true"
      # Do not expose containers unless explicitly told so
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      traefik-net: null
      backend-net:
        ipv4_address: ${TRAEFIK_IP}
    volumes:
      # traefik static config
      - ${DATAPATH}/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      # dynamic config
      - ${DATAPATH}/traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      # letsencrypt data  
      - ${DATAPATH}/traefik/acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock:ro

  nginx-test:
    image: nginx:latest
    hostname: "nginx-test"
    container_name: "nginx-test"
    depends_on:
      - traefik
    networks:
      traefik-net: null
      backend-net: null

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx1.entrypoints=websecure"
      - "traefik.http.routers.nginx1.rule=Host(`marven.es`)"
      - "traefik.http.routers.nginx1.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.nginx1.tls=true"



