version: "3"

services:
  whoami:
    image: "traefik/whoami"
    hostname: "whoami"
    container_name: "whoami"
    depends_on:
      - traefik
    ports:
      - "8501:8501" # HTTP port (host:container)
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`${MYDOMAIN}`) && PathPrefix(`/whoami`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certResolver=myLetsEncripCert"
      - "traefik.http.routers.whoami.tls=true"
    networks:
      - traefik-net
